name: run unit tests of feature branches

on:
  push:
    branches:
      'feature/*'

jobs:
  run-unit-test:
      runs-on: windows-latest

    steps:
       - name: Checkout
          uses: actions/checkout@v4.1.7

        - name: run unit test
        - run: npm test
    
